FROM node:10-alpine as pre-step
 
WORKDIR /app
 
COPY package.json .
 
RUN npm install
 
COPY . .
 
RUN npm run build:production


FROM nginx:alpine

COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /usr/share/nginx/html/hammad

COPY --from=pre-step /app/build /usr/share/nginx/html/hammad