apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: hammad-inventory-app
data:
  DATABASE_USER: postgres
  DATABASE_NAME: mydb

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: hammad-inventory-app
type: Opaque
data:
  POSTGRES_PASSWORD: bXlzZWNyZXRwYXNzd29yZA==  # Base64-encoded "mysecretpassword"
